// Copyright 2024 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Scanning files and memory for fonts.

#![allow(dead_code, unused_imports)]

use super::{
    family::{FamilyId, FamilyInfo},
    family_name::{FamilyName, FamilyNameMap},
    font::FontInfo,
};
use alloc::string::String;
use alloc::vec;
use hashbrown::HashMap;
use read_fonts::{
    FileRef, FontRef, TableProvider as _,
    tables::name,
    types::{NameId, Tag},
};
use smallvec::SmallVec;
#[cfg(feature = "std")]
use {
    super::scan_cache,
    super::source::{SourceId, SourceInfo, SourceKind},
    core::sync::atomic::{AtomicUsize, Ordering},
    hashbrown::HashSet,
    std::path::PathBuf,
    std::sync::Arc,
};
#[cfg(feature = "std")]
use {super::source::SourcePathMap, std::path::Path};

use alloc::vec::Vec;

#[cfg(feature = "std")]
/// Font collection generated by scanning the file system.
#[derive(Default)]
pub struct ScannedCollection {
    pub family_names: FamilyNameMap,
    pub postscript_names: HashMap<String, FamilyId>,
    pub data_paths: SourcePathMap,
    pub families: HashMap<FamilyId, FamilyInfo>,
}

#[cfg(feature = "std")]
impl ScannedCollection {
    /// Creates a new collection by scanning the given paths for
    /// font files.
    pub fn from_paths(paths: impl IntoIterator<Item = impl AsRef<Path>>, max_depth: u32) -> Self {
        scan_collection(paths, max_depth, None)
    }

    /// Creates a new collection by scanning the given paths for font files,
    /// using a persistent cache stored at `cache_path` to skip parsing
    /// files that haven't changed since the last scan.
    ///
    /// The cache is created or refreshed as needed. If it can't be read or
    /// written, the scan still succeeds without it.
    pub fn from_paths_cached(
        paths: impl IntoIterator<Item = impl AsRef<Path>>,
        max_depth: u32,
        cache_path: &Path,
    ) -> Self {
        scan_collection(paths, max_depth, Some(cache_path))
    }
}

/// Font generated by scanning the file system or a memory buffer.
pub struct ScannedFont<'a> {
    pub font: FontRef<'a>,
    #[cfg(feature = "std")]
    pub path: Option<&'a Path>,
    pub index: u32,
    pub name_table: name::Name<'a>,
}

impl<'a> ScannedFont<'a> {
    /// Returns the name string for the given identifier.
    pub fn english_or_first_name(&self, id: NameId) -> Option<name::NameString<'a>> {
        english_or_first(&self.name_table, id)
    }
}

#[cfg(feature = "std")]
/// Scans paths and invokes the given function for each font discovered.
pub fn scan_paths(
    paths: impl IntoIterator<Item = impl AsRef<Path>>,
    max_depth: u32,
    mut f: impl FnMut(&ScannedFont<'_>),
) {
    for path in paths {
        scan_path_impl(path.as_ref(), max_depth, &mut f, 0);
    }
}

/// Scans a memory buffer and invokes the given function for each font
/// discovered.
pub fn scan_memory<'a>(buf: &'a [u8], mut f: impl FnMut(&ScannedFont<'a>)) {
    #[allow(clippy::unit_arg)]
    scan_memory_impl(buf, ScanMemoryPathType::default(), &mut f);
}

#[cfg(feature = "std")]
fn scan_collection(
    paths: impl IntoIterator<Item = impl AsRef<Path>>,
    max_depth: u32,
    cache_path: Option<&Path>,
) -> ScannedCollection {
    let files = collect_font_files(paths, max_depth);
    let records = match cache_path {
        Some(cache_path) => parse_files_cached(&files, cache_path),
        None => {
            let paths: Vec<PathBuf> = files.into_iter().map(|(path, _)| path).collect();
            parse_files(&paths)
        }
    };
    let mut collection = ScannedCollection::default();
    let mut families: HashMap<FamilyId, (FamilyName, SmallVec<[FontInfo; 4]>)> = HashMap::default();
    for record in records {
        let [first_name, other_names @ ..] = record.names.as_slice() else {
            continue;
        };
        collection.data_paths.insert(record.font.source());
        let name = collection.family_names.get_or_insert(first_name);
        for other_name in other_names {
            collection.family_names.add_alias(name.id(), other_name);
        }
        collection
            .postscript_names
            .insert(record.postscript_name, name.id());
        families
            .entry(name.id())
            .or_insert_with(|| (name.clone(), SmallVec::default()))
            .1
            .push(record.font);
    }
    collection.families.extend(
        families
            .drain()
            .map(|(id, (name, fonts))| (id, FamilyInfo::new(name, fonts))),
    );
    collection
}

#[cfg(feature = "std")]
pub(crate) struct FontRecord {
    pub(crate) names: Vec<String>,
    pub(crate) postscript_name: String,
    pub(crate) font: FontInfo,
}

/// Expands the given paths into a deduplicated list of files (with their
/// modification stamps, where cheaply available), walking directories up
/// to `max_depth`.
#[cfg(feature = "std")]
fn collect_font_files(
    paths: impl IntoIterator<Item = impl AsRef<Path>>,
    max_depth: u32,
) -> Vec<(PathBuf, Option<scan_cache::FileStamp>)> {
    let mut seen = HashMap::default();
    for path in paths {
        collect_path(path.as_ref(), max_depth, 0, &mut seen);
    }
    seen.into_iter().collect()
}

#[cfg(feature = "std")]
fn collect_path(
    path: &Path,
    max_depth: u32,
    depth: u32,
    seen: &mut HashMap<PathBuf, Option<scan_cache::FileStamp>>,
) {
    let Ok(metadata) = path.metadata() else {
        return;
    };
    if metadata.is_dir() {
        if depth > max_depth {
            return;
        }
        walk_dir(path, max_depth, depth, seen);
    } else {
        seen.entry(path.to_path_buf())
            .or_insert_with(|| scan_cache::FileStamp::from_metadata(&metadata));
    }
}

/// Collects the files in the directory at `path` (which is at `depth`),
/// recursing into subdirectories up to `max_depth`.
///
/// On macOS, `getattrlistbulk` retrieves each entry's name, type, and
/// modification stamp in a single batched syscall, avoiding a separate
/// `stat` for every file.
#[cfg(all(feature = "std", target_os = "macos"))]
fn walk_dir(
    path: &Path,
    max_depth: u32,
    depth: u32,
    seen: &mut HashMap<PathBuf, Option<scan_cache::FileStamp>>,
) {
    use getattrlistbulk::{ObjectType, RequestedAttributes, read_dir};
    let attrs = RequestedAttributes {
        name: true,
        object_type: true,
        modified_time: true,
        size: true,
        ..Default::default()
    };
    let Ok(entries) = read_dir(path, attrs) else {
        return;
    };
    for entry in entries.filter_map(|entry| entry.ok()) {
        let child = path.join(&entry.name);
        match entry.object_type {
            Some(ObjectType::Directory) => {
                if depth < max_depth {
                    walk_dir(&child, max_depth, depth + 1, seen);
                }
            }
            Some(ObjectType::Regular) => {
                let stamp = entry
                    .modified_time
                    .zip(entry.size)
                    .and_then(|(modified, size)| scan_cache::FileStamp::new(modified, size));
                seen.entry(child).or_insert(stamp);
            }
            // Resolve symlinks (and anything unexpected) through the
            // generic path, which follows them via `metadata`.
            _ => collect_path(&child, max_depth, depth + 1, seen),
        }
    }
}

#[cfg(all(feature = "std", not(target_os = "macos")))]
fn walk_dir(
    path: &Path,
    max_depth: u32,
    depth: u32,
    seen: &mut HashMap<PathBuf, Option<scan_cache::FileStamp>>,
) {
    let Ok(entries) = std::fs::read_dir(path) else {
        return;
    };
    for entry in entries.filter_map(|entry| entry.ok()) {
        collect_path(entry.path().as_path(), max_depth, depth + 1, seen);
    }
}

/// Reads and parses the given font files, distributing the work across
/// available CPU cores.
#[cfg(feature = "std")]
fn parse_files(files: &[PathBuf]) -> Vec<FontRecord> {
    parse_files_impl(files)
        .into_iter()
        .flat_map(|(_, records)| records)
        .collect()
}

/// As [`parse_files`], but reusing results from and refreshing the cache
/// stored at `cache_path`.
#[cfg(feature = "std")]
fn parse_files_cached(
    files: &[(PathBuf, Option<scan_cache::FileStamp>)],
    cache_path: &Path,
) -> Vec<FontRecord> {
    let mut cache = scan_cache::load(cache_path).unwrap_or_default();
    let cached_file_count = cache.len();

    // Partition into cache hits and files that need parsing.
    let mut results: Vec<(&Path, Option<scan_cache::FileStamp>, Vec<FontRecord>)> =
        Vec::with_capacity(files.len());
    let mut misses: Vec<(&Path, Option<scan_cache::FileStamp>)> = Vec::new();
    for (path, stamp) in files {
        let stamp = stamp.or_else(|| {
            std::fs::metadata(path)
                .ok()
                .as_ref()
                .and_then(scan_cache::FileStamp::from_metadata)
        });
        match cache.remove(path.as_path()) {
            Some(cached) if stamp == Some(cached.stamp) => {
                results.push((path, stamp, cached.records));
            }
            _ => misses.push((path.as_path(), stamp)),
        }
    }
    let hit_count = results.len();

    // Parse the files that missed the cache in parallel.
    let miss_paths: Vec<PathBuf> = misses
        .iter()
        .map(|(path, _)| (*path).to_path_buf())
        .collect();
    for (index, records) in parse_files_impl(&miss_paths) {
        let (path, stamp) = misses[index];
        results.push((path, stamp, records));
    }

    // Refresh the cache if anything was parsed or any cached file no longer
    // exists in the scanned set.
    let stale_cached_files = cached_file_count - hit_count;
    if !misses.is_empty() || stale_cached_files > 0 {
        let _ = scan_cache::save(
            cache_path,
            results
                .iter()
                .filter_map(|(path, stamp, records)| Some((*path, (*stamp)?, records.as_slice()))),
        );
    }

    results
        .into_iter()
        .flat_map(|(_, _, records)| records)
        .collect()
}

/// Reads and parses the given font files in parallel, returning the records
/// grouped by file (in arbitrary order).
#[cfg(feature = "std")]
fn parse_files_impl(files: &[PathBuf]) -> Vec<(usize, Vec<FontRecord>)> {
    let num_threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(1)
        .min(files.len());
    if num_threads <= 1 {
        return files
            .iter()
            .enumerate()
            .map(|(index, path)| {
                let mut records = Vec::new();
                parse_file(path, &mut records);
                (index, records)
            })
            .collect();
    }
    let cursor = AtomicUsize::new(0);
    std::thread::scope(|scope| {
        let handles: Vec<_> = (0..num_threads)
            .map(|_| {
                scope.spawn(|| {
                    let mut results = Vec::new();
                    loop {
                        let index = cursor.fetch_add(1, Ordering::Relaxed);
                        let Some(path) = files.get(index) else {
                            break;
                        };
                        let mut records = Vec::new();
                        parse_file(path, &mut records);
                        results.push((index, records));
                    }
                    results
                })
            })
            .collect();
        handles
            .into_iter()
            .flat_map(|handle| handle.join().unwrap_or_default())
            .collect()
    })
}

#[cfg(feature = "std")]
fn parse_file(path: &Path, out: &mut Vec<FontRecord>) {
    let Ok(mut file) = std::fs::File::open(path) else {
        return;
    };
    let Ok(file_len) = file.metadata().map(|metadata| metadata.len()) else {
        return;
    };
    let Some((buffer, font_indices)) = read_font_metadata(&mut file, file_len) else {
        return;
    };
    let mut source: Option<SourceInfo> = None;
    let mut name_pool = vec![];
    let mut names = vec![];
    for index in font_indices {
        let Ok(font) = FontRef::from_index(&buffer, index) else {
            continue;
        };
        let Ok(name_table) = font.name() else {
            continue;
        };
        name_pool.append(&mut names);
        if !all_names(
            &name_table,
            NameId::TYPOGRAPHIC_FAMILY_NAME,
            &mut name_pool,
            &mut names,
        ) && !all_names(&name_table, NameId::FAMILY_NAME, &mut name_pool, &mut names)
        {
            continue;
        }
        let Some(postscript_name) = english_or_first(&name_table, NameId::POSTSCRIPT_NAME)
            .map(|name| name.chars().collect::<String>())
        else {
            continue;
        };
        let source = source
            .get_or_insert_with(|| {
                SourceInfo::new(SourceId::new(), SourceKind::Path(Arc::from(path)))
            })
            .clone();
        let Some(font) = FontInfo::from_font_ref(&font, source, index) else {
            continue;
        };
        out.push(FontRecord {
            names: core::mem::take(&mut names),
            postscript_name,
            font,
        });
    }
}

/// Tables needed to build a [`FontRecord`] for a font.
#[cfg(feature = "std")]
const METADATA_TABLES: [Tag; 6] = [
    Tag::new(b"OS/2"),
    Tag::new(b"cmap"),
    Tag::new(b"fvar"),
    Tag::new(b"head"),
    Tag::new(b"name"),
    Tag::new(b"post"),
];

/// Reads the parts of a font file needed to build [`FontRecord`]s.
///
/// Rather than memory mapping the file (page faults on mapped memory
/// serialize in the kernel, which defeats parallel scanning) or reading the
/// whole file (font files can be very large), this reads only the table
/// directories and metadata tables into a sparse buffer that preserves the
/// original file offsets, so that offsets recorded during scanning (such as
/// the [`CharmapIndex`](crate::CharmapIndex) subtable offset) remain valid
/// for the full font data loaded later.
///
/// Returns the buffer along with the indices of the fonts to scan. Fonts
/// with an `hvgl` table are excluded as we can't currently render them.
#[cfg(feature = "std")]
fn read_font_metadata(file: &mut std::fs::File, file_len: u64) -> Option<(Vec<u8>, Vec<u32>)> {
    use std::io::{Read as _, Seek as _, SeekFrom};

    /// An implausible number of fonts or tables, used to reject junk files.
    const SANITY_LIMIT: u32 = 4096;
    const HVGL: Tag = Tag::new(b"hvgl");
    const TTCF: Tag = Tag::new(b"ttcf");

    fn read_at(file: &mut std::fs::File, offset: u64, buf: &mut [u8]) -> Option<()> {
        file.seek(SeekFrom::Start(offset)).ok()?;
        file.read_exact(buf).ok()
    }

    let mut header = [0_u8; 12];
    read_at(file, 0, &mut header)?;

    // Byte ranges of the file that we need to read.
    let mut segments: Vec<(u64, u64)> = vec![(0, header.len() as u64)];

    // Offsets of the table directory for each font in the file.
    let dir_offsets: Vec<u64> = if Tag::new(&[header[0], header[1], header[2], header[3]]) == TTCF {
        let num_fonts = u32::from_be_bytes([header[8], header[9], header[10], header[11]]);
        if num_fonts > SANITY_LIMIT {
            return None;
        }
        let mut offsets = vec![0_u8; num_fonts as usize * 4];
        read_at(file, 12, &mut offsets)?;
        segments.push((0, 12 + offsets.len() as u64));
        offsets
            .chunks_exact(4)
            .map(|chunk| u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]) as u64)
            .collect()
    } else {
        vec![0]
    };

    let mut font_indices = Vec::new();
    let mut record_buf = Vec::new();
    'fonts: for (font_index, dir_offset) in dir_offsets.iter().copied().enumerate() {
        let mut dir_header = [0_u8; 12];
        if read_at(file, dir_offset, &mut dir_header).is_none() {
            continue;
        }
        let num_tables = u16::from_be_bytes([dir_header[4], dir_header[5]]);
        if u32::from(num_tables) > SANITY_LIMIT {
            continue;
        }
        record_buf.resize(usize::from(num_tables) * 16, 0);
        if read_at(file, dir_offset + 12, &mut record_buf).is_none() {
            continue;
        }
        let mut table_segments: SmallVec<[(u64, u64); 8]> = SmallVec::new();
        for record in record_buf.chunks_exact(16) {
            let tag = Tag::new(&[record[0], record[1], record[2], record[3]]);
            if tag == HVGL {
                // We can't currently render hvgl outlines so reject the font.
                continue 'fonts;
            }
            if METADATA_TABLES.contains(&tag) {
                let offset = u64::from(u32::from_be_bytes([
                    record[8], record[9], record[10], record[11],
                ]));
                let len = u64::from(u32::from_be_bytes([
                    record[12], record[13], record[14], record[15],
                ]));
                let end = offset + len;
                if end > file_len {
                    // Out of bounds table. Leave it unread so parsing treats
                    // it as absent or invalid.
                    continue;
                }
                table_segments.push((offset, end));
            }
        }
        segments.push((dir_offset, dir_offset + 12 + record_buf.len() as u64));
        segments.extend_from_slice(&table_segments);
        font_indices.push(u32::try_from(font_index).ok()?);
    }
    if font_indices.is_empty() {
        return None;
    }

    // Merge overlapping segments and read them into a sparse buffer sized to
    // cover the furthest extent we need.
    fn slice_range(buf: &mut [u8], (start, end): (u64, u64)) -> Option<&mut [u8]> {
        buf.get_mut(usize::try_from(start).ok()?..usize::try_from(end).ok()?)
    }
    segments.sort_unstable();
    let buffer_len = usize::try_from(segments.iter().map(|(_, end)| *end).max()?).ok()?;
    let mut buffer = vec![0_u8; buffer_len];
    let mut segments = segments.into_iter();
    let mut current = segments.next()?;
    for (start, end) in segments {
        if start <= current.1 {
            current.1 = current.1.max(end);
        } else {
            read_at(file, current.0, slice_range(&mut buffer, current)?)?;
            current = (start, end);
        }
    }
    read_at(file, current.0, slice_range(&mut buffer, current)?)?;
    Some((buffer, font_indices))
}

#[cfg(feature = "std")]
fn scan_path_impl(
    path: &Path,
    max_depth: u32,
    f: &mut impl FnMut(&ScannedFont<'_>),
    depth: u32,
) -> Option<()> {
    let metadata = path.metadata().ok()?;
    if metadata.is_dir() {
        if depth > max_depth {
            return None;
        }
        for entry in std::fs::read_dir(path).ok()?.filter_map(|entry| entry.ok()) {
            scan_path_impl(entry.path().as_path(), max_depth, f, depth + 1);
        }
    } else {
        let file = std::fs::File::open(path).ok()?;
        let mapped = unsafe { memmap2::Mmap::map(&file) }.ok()?;
        scan_memory_impl(&mapped, Some(path), f);
    }
    Some(())
}

#[cfg(feature = "std")]
type ScanMemoryPathType<'a> = Option<&'a Path>;

#[cfg(not(feature = "std"))]
type ScanMemoryPathType<'a> = ();

fn scan_memory_impl<'a>(
    data: &'a [u8],
    path: ScanMemoryPathType<'a>,
    f: &mut impl FnMut(&ScannedFont<'a>),
) -> Option<()> {
    let font_file = FileRef::new(data).ok()?;
    match font_file {
        FileRef::Font(font) => {
            scan_font(font, path, 0, f);
        }
        FileRef::Collection(collection) => {
            for i in 0..collection.len() {
                let Ok(font) = collection.get(i) else {
                    continue;
                };
                scan_font(font, path, i, f);
            }
        }
    }
    Some(())
}

fn scan_font<'a>(
    font: FontRef<'a>,
    #[allow(unused)] path: ScanMemoryPathType<'a>,
    index: u32,
    f: &mut impl FnMut(&ScannedFont<'a>),
) -> Option<()> {
    // We can't currently render hvgl fonts so reject them
    if font.table_data(Tag::new(b"hvgl")).is_some() {
        return None;
    }
    let name_table = font.name().ok()?;
    f(&ScannedFont {
        font,
        #[cfg(feature = "std")]
        path,
        index,
        name_table,
    });
    Some(())
}

fn all_names(
    name_table: &name::Name<'_>,
    id: NameId,
    pool: &mut Vec<String>,
    result: &mut Vec<String>,
) -> bool {
    // Find the "English or first" name first. We'll use that as the default
    // name.
    let mut best_index = 0;
    let mut best_rank = -1;
    let mut best_record = None;
    for (i, record) in name_table
        .name_record()
        .iter()
        .enumerate()
        .filter(|x| x.1.name_id() == id)
    {
        let rank = match (i, record.language_id()) {
            (_, 0x0409) => {
                best_index = i;
                best_record = Some(record);
                break;
            }
            (_, 0) => 2,
            (0, _) => 1,
            _ => continue,
        };
        if rank > best_rank {
            best_rank = rank;
            best_index = i;
            best_record = Some(record);
        }
    }
    // Add the "best" name first
    if let Some(best) = best_record.and_then(|rec| rec.string(name_table.string_data()).ok()) {
        let mut str = pool.pop().unwrap_or_default();
        str.clear();
        str.extend(best.chars());
        if !str.is_empty() {
            result.push(str);
        } else {
            pool.push(str);
        }
    }
    // And then the rest
    for (i, record) in name_table
        .name_record()
        .iter()
        .enumerate()
        .filter(|x| x.1.name_id() == id)
    {
        if best_record.is_some() && i == best_index {
            continue;
        }
        let Ok(name_str) = record.string(name_table.string_data()) else {
            continue;
        };
        let mut str = pool.pop().unwrap_or_default();
        str.clear();
        str.extend(name_str.chars());
        if !str.is_empty() {
            result.push(str);
        } else {
            pool.push(str);
        }
    }
    !result.is_empty()
}

fn english_or_first<'a>(names: &name::Name<'a>, id: NameId) -> Option<name::NameString<'a>> {
    let mut best_rank = -1;
    let mut best_record = None;
    for (i, record) in names
        .name_record()
        .iter()
        .enumerate()
        .filter(|x| x.1.name_id() == id)
    {
        let rank = match (i, record.language_id()) {
            (_, 0x0409) => {
                best_record = Some(record);
                break;
            }
            (_, 0) => 2,
            (0, _) => 1,
            _ => continue,
        };
        if rank > best_rank {
            best_rank = rank;
            best_record = Some(record);
        }
    }
    best_record.and_then(|record| record.string(names.string_data()).ok())
}

#[cfg(all(test, feature = "std"))]
mod tests {
    use super::*;
    use alloc::format;
    use alloc::string::ToString;

    /// Font files shipped in the repo for use as test assets.
    const ASSETS: &[&str] = &[
        "../parley_dev/assets/fonts/roboto_fonts/Roboto-Regular.ttf",
        "../parley_dev/assets/fonts/arimo_fonts/Arimo-VariableFont_wght.ttf",
        "../parley_dev/assets/fonts/noto_fonts/NotoKufiArabic-Regular.otf",
    ];

    fn summarize(collection: &ScannedCollection) -> Vec<(String, usize)> {
        let mut summary: Vec<_> = collection
            .families
            .values()
            .map(|family| (family.name().to_string(), family.fonts().len()))
            .collect();
        summary.sort();
        summary
    }

    fn font_key(font: &FontInfo) -> (PathBuf, u32) {
        let SourceKind::Path(path) = font.source().kind() else {
            unreachable!()
        };
        (path.to_path_buf(), font.index())
    }

    fn sorted_fonts(collection: &ScannedCollection, family_name: &str) -> Vec<FontInfo> {
        let mut fonts: Vec<FontInfo> = collection
            .families
            .values()
            .find(|family| family.name() == family_name)
            .unwrap()
            .fonts()
            .to_vec();
        fonts.sort_by_key(font_key);
        fonts
    }

    #[test]
    fn cached_scan_matches_uncached() {
        let dir = std::env::temp_dir().join(format!("fontique-scan-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let fonts_dir = dir.join("fonts");
        std::fs::create_dir_all(&fonts_dir).unwrap();
        for asset in ASSETS {
            let asset = Path::new(env!("CARGO_MANIFEST_DIR")).join(asset);
            std::fs::copy(&asset, fonts_dir.join(asset.file_name().unwrap())).unwrap();
        }
        let cache_path = dir.join("cache.bin");

        let uncached = ScannedCollection::from_paths([&fonts_dir], 2);
        // Cold cache run (writes the cache).
        let cold = ScannedCollection::from_paths_cached([&fonts_dir], 2, &cache_path);
        assert!(cache_path.exists());
        // Warm cache run.
        let warm = ScannedCollection::from_paths_cached([&fonts_dir], 2, &cache_path);

        assert_eq!(summarize(&uncached), summarize(&cold));
        assert_eq!(summarize(&uncached), summarize(&warm));
        let mut expected_ps: Vec<_> = uncached.postscript_names.keys().collect();
        let mut warm_ps: Vec<_> = warm.postscript_names.keys().collect();
        expected_ps.sort();
        warm_ps.sort();
        assert_eq!(expected_ps, warm_ps);

        // Every font attribute should round-trip through the cache.
        for (family_name, _) in summarize(&uncached) {
            let expected = sorted_fonts(&uncached, &family_name);
            let cached = sorted_fonts(&warm, &family_name);
            assert_eq!(expected.len(), cached.len());
            for (a, b) in expected.iter().zip(&cached) {
                assert_eq!(a.index(), b.index());
                assert_eq!(a.width(), b.width());
                assert_eq!(a.style(), b.style());
                assert_eq!(a.weight(), b.weight());
                assert_eq!(a.charmap_index(), b.charmap_index());
                assert_eq!(a.axes().len(), b.axes().len());
                for (axis_a, axis_b) in a.axes().iter().zip(b.axes()) {
                    assert_eq!(axis_a.tag, axis_b.tag);
                    assert_eq!(axis_a.min, axis_b.min);
                    assert_eq!(axis_a.max, axis_b.max);
                    assert_eq!(axis_a.default, axis_b.default);
                }
                assert_eq!(a.has_weight_axis(), b.has_weight_axis());
            }
        }

        // A changed file should be re-parsed: replace Roboto with Arimo
        // (and ensure the modification time changes).
        let replaced = fonts_dir.join("Roboto-Regular.ttf");
        let arimo = Path::new(env!("CARGO_MANIFEST_DIR")).join(ASSETS[1]);
        std::fs::copy(&arimo, &replaced).unwrap();
        let old = std::time::SystemTime::now() - core::time::Duration::from_secs(1000);
        std::fs::File::options()
            .write(true)
            .open(&replaced)
            .unwrap()
            .set_modified(old)
            .unwrap();
        let rescanned = ScannedCollection::from_paths_cached([&fonts_dir], 2, &cache_path);
        assert!(
            !rescanned
                .families
                .values()
                .any(|family| family.name() == "Roboto"),
            "stale cache entry for changed file"
        );
        assert_eq!(sorted_fonts(&rescanned, "Arimo").len(), 2);

        let _ = std::fs::remove_dir_all(&dir);
    }
}
