// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Span boxes: the boxes generated by the style spans of a [`TreeBuilder`](crate::TreeBuilder).
//!
//! Unlike an [`InlineBox`](crate::InlineBox), a span box is not atomic: its content is shaped,
//! wrapped and reordered like any other text. What it adds is an *edge* at each end
//! ([`TextStyle::inline_start`](crate::TextStyle::inline_start) and
//! [`TextStyle::inline_end`](crate::TextStyle::inline_end)). An edge is a layout item of its own
//! (`LayoutItemKind::SpanStart` / `LayoutItemKind::SpanEnd`) with a fixed advance, placed between
//! shaped runs.
//!
//! Only span boxes that need them get edge items: those with a non-zero edge, and those without
//! any content (which have nothing else to position them by). All other span boxes are located
//! through the styles of the content on a line.

use alloc::vec::Vec;
use core::ops::Range;

/// Sentinel for "no span box".
pub(crate) const NO_SPAN_BOX: u32 = u32::MAX;

/// The box generated by a style span.
#[derive(PartialEq, Debug, Clone)]
pub(crate) struct LayoutSpanBox {
    /// Style index of the span.
    pub(crate) style_index: u16,
    /// Index of the closest enclosing span box, or [`NO_SPAN_BOX`].
    pub(crate) parent: u32,
    /// Advance before the span's content.
    pub(crate) inline_start: f32,
    /// Advance after the span's content.
    pub(crate) inline_end: f32,
    /// The range of text between the span's start and end.
    pub(crate) text_range: Range<usize>,
    /// Whether the span box has `SpanStart` and `SpanEnd` layout items.
    pub(crate) has_edge_items: bool,
}

impl LayoutSpanBox {
    /// Whether either of the span box's edges is non-zero.
    #[inline(always)]
    pub(crate) fn has_edges(&self) -> bool {
        self.inline_start != 0. || self.inline_end != 0.
    }
}

/// Which edge of a span box a [`SpanBoundary`] is.
#[derive(PartialEq, Eq, Debug, Clone, Copy)]
pub(crate) enum SpanEdge {
    Start,
    End,
}

/// The position of one edge of a span box within the text.
#[derive(PartialEq, Debug, Clone, Copy)]
pub(crate) struct SpanBoundary {
    /// The byte offset into the text at which the edge is placed.
    pub(crate) index: usize,
    /// The number of inline boxes that had been pushed before this edge, which orders the edge
    /// relative to inline boxes at the same byte offset.
    pub(crate) inline_box_count: usize,
    /// Index of the span box.
    pub(crate) span_box: u32,
    pub(crate) edge: SpanEdge,
}

/// An item placed between shaped runs: an inline box or an edge of a span box.
#[derive(PartialEq, Debug, Clone, Copy)]
pub(crate) enum InlineItem {
    /// Index of the inline box.
    InlineBox(usize),
    /// Index of the span box, and which of its edges.
    SpanEdge(u32, SpanEdge),
}

/// Merges inline boxes (given by their text indices, in text index order) and span boundaries (in
/// text order) into a single sequence in layout order, as `(text index, item)`.
pub(crate) fn merge_inline_items(
    inline_box_indices: impl Iterator<Item = usize>,
    boundaries: &[SpanBoundary],
    out: &mut Vec<(usize, InlineItem)>,
) {
    out.clear();
    let mut boundaries = boundaries.iter().peekable();
    for (box_idx, box_text_index) in inline_box_indices.enumerate() {
        while let Some(boundary) = boundaries.peek() {
            let is_before_box = boundary.index < box_text_index
                || (boundary.index == box_text_index && boundary.inline_box_count <= box_idx);
            if !is_before_box {
                break;
            }
            out.push((
                boundary.index,
                InlineItem::SpanEdge(boundary.span_box, boundary.edge),
            ));
            boundaries.next();
        }
        out.push((box_text_index, InlineItem::InlineBox(box_idx)));
    }
    for boundary in boundaries {
        out.push((
            boundary.index,
            InlineItem::SpanEdge(boundary.span_box, boundary.edge),
        ));
    }
}
