// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Per-style inline box metrics.
//!
//! Every entry of the style table corresponds to an inline box (the root style being the block
//! container's "strut", see CSS 2 §10.8). This module resolves, once per layout, the metrics of
//! each of those boxes from the style's *primary* font and `line-height`, and computes the
//! baseline shift implied by its `vertical-align` relative to its parent.

use alloc::vec::Vec;

use fontique::{Query, QueryFamily};
use parley_engine::{FontInstance, FontMetrics};

use crate::resolve::{ResolveContext, ResolvedStyle};
use crate::style::Brush;
use crate::{FontContext, FontData, InlineBox, LineHeight, VerticalAlign};

/// Metrics of the inline box generated by one style table entry.
///
/// All distances are in layout units and measured from the box's own baseline; `over`/`ascent`
/// extend upwards, `under`/`descent` downwards.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub(crate) struct StyleMetrics {
    /// Ascent of the primary font (the top of the content area).
    pub(crate) ascent: f32,
    /// Descent of the primary font (the bottom of the content area).
    pub(crate) descent: f32,
    /// x-height of the primary font, used by `vertical-align: middle`.
    pub(crate) x_height: f32,
    /// Distance from the baseline to the top of the line-height expanded inline box.
    pub(crate) over: f32,
    /// Distance from the baseline to the bottom of the line-height expanded inline box.
    pub(crate) under: f32,
    /// Resolved `line-height` (`over + under`).
    pub(crate) line_height: f32,
    /// Offset of this box's baseline above the baseline of its [aligned subtree's] root.
    ///
    /// [aligned subtree's]: Self::aligned_subtree
    pub(crate) baseline_offset: f32,
    /// Style index of the root of the aligned subtree this box belongs to: `0` for the root
    /// inline box, or the nearest ancestor (or self) with `vertical-align: top | bottom`.
    pub(crate) aligned_subtree: u16,
    /// Style index of the parent inline box (`0`, itself, for the root).
    pub(crate) parent: u16,
    /// The style's font size, against which `sub`/`super` of children are resolved.
    pub(crate) font_size: f32,
}

/// Resolve the [`StyleMetrics`] of every style in `styles`, in table order.
///
/// Relies on the style table being ordered parent-first (`style.parent <= index`), which both
/// style builders guarantee.
pub(crate) fn resolve_style_metrics<B: Brush>(
    rcx: &ResolveContext,
    fcx: &mut FontContext,
    styles: &[ResolvedStyle<B>],
    quantize: bool,
    out: &mut Vec<StyleMetrics>,
) {
    out.clear();
    out.reserve(styles.len());

    let mut query = fcx.collection.query(&mut fcx.source_cache);

    for (index, style) in styles.iter().enumerate() {
        let font_metrics = primary_font(&mut query, rcx, style)
            .and_then(|font| {
                FontMetrics::from_variations(
                    &font,
                    style.font_size,
                    rcx.variations(style.font_variations).unwrap_or(&[]),
                )
            })
            .unwrap_or_else(|| fallback_metrics(style.font_size));

        let line_height = match style.line_height {
            LineHeight::Absolute(value) => value,
            LineHeight::FontSizeRelative(value) => value * style.font_size,
            LineHeight::MetricsRelative(value) => {
                (font_metrics.ascent + font_metrics.descent + font_metrics.leading) * value
            }
        };

        let mut metrics = StyleMetrics::from_font(&font_metrics, line_height, quantize);
        metrics.parent = style.parent;
        metrics.font_size = style.font_size;

        let parent_index = usize::from(style.parent);
        debug_assert!(
            parent_index <= index,
            "style table must be ordered parent-first"
        );
        if index == 0 || parent_index >= index {
            // The root inline box (the strut).
            metrics.parent = index as u16;
            metrics.baseline_offset = 0.;
            metrics.aligned_subtree = 0;
        } else {
            let parent = &out[parent_index];
            match style.vertical_align {
                VerticalAlign::Top | VerticalAlign::Bottom => {
                    metrics.baseline_offset = 0.;
                    metrics.aligned_subtree = index as u16;
                }
                align => {
                    let shift = shift_from_parent(align, metrics.over, metrics.under, parent);
                    metrics.baseline_offset = parent.baseline_offset + shift;
                    metrics.aligned_subtree = parent.aligned_subtree;
                }
            }
        }

        out.push(metrics);
    }
}

impl StyleMetrics {
    /// Build the box metrics from primary font metrics and a resolved `line-height`.
    ///
    /// The half-leading is distributed as in CSS 2 §10.8.1. With `quantize`, ascent and descent
    /// are rounded to whole pixels and the leading above the baseline is floored, mirroring how
    /// text runs are placed.
    pub(crate) fn from_font(font: &FontMetrics, line_height: f32, quantize: bool) -> Self {
        let (ascent, descent) = if quantize {
            (font.ascent.round(), font.descent.round())
        } else {
            (font.ascent, font.descent)
        };
        let half_leading = (line_height - (ascent + descent)) / 2.;
        let over = if quantize {
            ascent + half_leading.floor()
        } else {
            ascent + half_leading
        };
        let under = line_height - over;
        let x_height = font.x_height.unwrap_or(ascent * 0.5);
        Self {
            ascent,
            descent,
            x_height: if quantize { x_height.round() } else { x_height },
            over,
            under,
            line_height,
            baseline_offset: 0.,
            aligned_subtree: 0,
            parent: 0,
            font_size: 0.,
        }
    }
}

/// The baseline shift (positive upwards) of a box extending `over` above and `under` below its
/// baseline, relative to the baseline of its `parent` inline box, for a parent-relative
/// `vertical-align` value. Line-relative values (`top`, `bottom`) yield no shift.
pub(crate) fn shift_from_parent(
    align: VerticalAlign,
    over: f32,
    under: f32,
    parent: &StyleMetrics,
) -> f32 {
    match align {
        VerticalAlign::Baseline | VerticalAlign::Top | VerticalAlign::Bottom => 0.,
        VerticalAlign::Length(length) => length,
        // Constants as used by WebKit and Blink.
        VerticalAlign::Sub => -(parent.font_size / 5.),
        VerticalAlign::Super => parent.font_size / 3.,
        VerticalAlign::TextTop => parent.ascent - over,
        VerticalAlign::TextBottom => under - parent.descent,
        VerticalAlign::Middle => parent.x_height / 2. - (over - under) / 2.,
    }
}

/// Where an in-flow [`InlineBox`] sits relative to the baseline of its aligned subtree.
#[derive(Clone, Copy, Debug)]
pub(crate) struct InlineBoxPlacement {
    /// Style index of the aligned subtree root (see [`StyleMetrics::aligned_subtree`]).
    pub(crate) aligned_subtree: u16,
    /// Offset of the box's baseline above the subtree root's baseline.
    pub(crate) baseline_offset: f32,
    /// Height of the box above its baseline.
    pub(crate) ascent: f32,
    /// Height of the box below its baseline.
    pub(crate) descent: f32,
}

/// Resolve the parent-relative alignment of `inline_box` against the inline box of the style
/// containing it (`parent_style`).
///
/// A box without an explicit baseline sits on the baseline, i.e. it is all ascent. For
/// `vertical-align: top | bottom` the returned offset is relative to the parent's subtree, but
/// such boxes are positioned against the line box instead (see `Line::inline_box_y`).
pub(crate) fn inline_box_placement(
    inline_box: &InlineBox,
    parent_style: u16,
    style_metrics: &[StyleMetrics],
) -> InlineBoxPlacement {
    let ascent = inline_box.baseline.unwrap_or(inline_box.height);
    let descent = inline_box.height - ascent;
    let parent = style_metrics
        .get(usize::from(parent_style))
        .copied()
        .unwrap_or_default();
    let shift = shift_from_parent(inline_box.vertical_align, ascent, descent, &parent);
    InlineBoxPlacement {
        aligned_subtree: parent.aligned_subtree,
        baseline_offset: parent.baseline_offset + shift,
        ascent,
        descent,
    }
}

/// Query the primary font of `style`: the first available face of its font stack.
fn primary_font<B: Brush>(
    query: &mut Query<'_>,
    rcx: &ResolveContext,
    style: &ResolvedStyle<B>,
) -> Option<FontInstance> {
    let families = rcx.stack(style.font_family).unwrap_or(&[]);
    query.set_families(families.iter().copied().map(QueryFamily::Id));
    query.set_attributes(fontique::Attributes {
        width: style.font_width,
        weight: style.font_weight,
        style: style.font_style,
    });
    let mut found = None;
    query.matches_with(|font| {
        found = Some(FontInstance {
            font: FontData {
                data: font.blob.clone(),
                index: font.index,
            },
            synthesis: font.synthesis,
        });
        fontique::QueryStatus::Stop
    });
    found
}

/// Metrics to use when no font is available at all.
///
/// These roughly match common Latin fonts, so that a layout without fonts still has plausible
/// line heights.
fn fallback_metrics(font_size: f32) -> FontMetrics {
    FontMetrics {
        ascent: font_size * 0.8,
        descent: font_size * 0.2,
        leading: 0.,
        underline_offset: 0.,
        underline_size: 0.,
        strikethrough_offset: 0.,
        strikethrough_size: 0.,
        cap_height: None,
        x_height: None,
    }
}
